name: Build Windows EXE

on:
  push:
    branches:
      - main  # Ejecuta el workflow cuando haya cambios en la rama 'main'
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  build:
    runs-on: windows-latest  # Usar un runner remoto de GitHub con Windows
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3  # Clona el repositorio en el runner

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Instalar Python 3.11

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip  # Actualiza pip
          pip install pyinstaller  # Instala PyInstaller

      - name: Crear ejecutable con PyInstaller
        run: |
          pyinstaller --name="ILO Tunnel Manager" --windowed \
            --add-data="ilo_tunnel/resources;resources" \
            --add-data="ilo_tunnel/ssh_manager.py;." \
            ilo_tunnel/main.py  # Ejecuta PyInstaller

      - name: Subir ejecutable como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: ilo-tunnel-exe
          path: dist/ILO\ Tunnel\ Manager.exe  # El ejecutable generado
